### ISSUE TITLE
Folding the screen to use a single screen issues.

### ISSUE THREAD

**Issue by zohim1608** [Archfx/duo-de#127]
### Acknowledgements

- [X] I have chosen an appropriate title.
- [X] All requested information has been provided properly.
- [X] This is not a feature request.
- [X] This issue is not a duplicate of an existing issue.
- [X] The issue is solely related to this GSI.
- [X] This issue occurs with the latest available build.
- [X] I am not running a custom vendor on my device.
- [X] This issue is not kernel related.
- [X] This issue is not related to Magisk/KernelSU/APatch.

### Info

- Device: Duo 1
- GSI version: Android 15 (well this is android version i guess)
- Vendor version:(idk how to check)
- I am on the latest current build thats available.

### Expected Behavior

When I fold the phone to use one screen it should work and display what it needs to and if I flip to the other screen it should go to that one straight away. The main home screen should also be how I left it when I then unfold it again.

### Current Behavior

When I fold the duo to use a single screen it is black and the screen that is at the back is the one on, not the screen I can see, when I flip the phone it just swaps and the screen I can see is always black. It takes a lot of tries and messing about to get the screen I can see to be the one that works. Also when I go back into unfolded mode two apps from my task bar on the home screen disappear and I have to re add them every time i fold and unfold the phone. 

### Steps to Reproduce

1. Fold the phone to use one screen
2. Flip to the other screen
3. Unfold back to double screen

**Comment by zohim1608** [comment]
I would like to add that today folding the phone to one screen completely reset my home screen layout

**Comment by Ethanol10** [comment]
I think the first part of your description is the same issue found in your previous issue: https://github.com/Archfx/duo-de/issues/124 

I was experiencing the same issue with the setting set to Dynamic, as the Posture state would get confused when the screen was flipped. This might be due to how the reading is collected during the fold, which can be ambiguous to interpret from the device's perspective. 

For now if you feel like you prioritise using a specific screen every time you open and fold to use a single screen, consider using the Left/Right setting instead of dynamic. However, this issue will persist until we can figure out a better way for dynamic to register appropriately.

**Comment by Ethanol10** [comment]
@Archfx maybe we need to disable the posture change when folded, similar to Stock 12L. When folded, at the moment of change the sensor is read, it sets the screen to display on, and from there the screen will not change beyond that until the screen has unfolded, and folded back to single screen postures again.

**Comment by zohim1608** [comment]
And do you know anything about it resetting the homescreen too and removing my apps from it when I do the same thing?

**Comment by Ethanol10** [comment]
No, Sadly that's still a continuing issue I have no solution for right now

**Comment by Archfx** [comment]
> @Archfx maybe we need to disable the posture change when folded, similar to Stock 12L. When folded, at the moment of change the sensor is read, it sets the screen to display on, and from there the screen will not change beyond that until the screen has unfolded, and folded back to single screen postures again.

It is a good idea. I also have trouble during extended periods of folded usage, suddenly it switches to dual panel mode without any change.

**Comment by Archfx** [comment]
This is fixed in latest build.

**Comment by itsleemcguire** [comment]
This issue still happening to me on latest build

**Comment by zohim1608** [comment]
Well the single screen issue seems fixed for now. Il have to see over time so thank you! However the home screen layout issue is still happening, when I fold the screen apps disappear from home screen.

**Comment by itsleemcguire** [comment]
If the single screen issue is this in the bug description "When I fold the duo to use a single screen it is black and the screen that is at the back is the one on, not the screen I can see, when I flip the phone it just swaps and the screen I can see is always black. It takes a lot of tries and messing about to get the screen I can see to be the one that works. "
Then that is still happening to me every time I wake the phone with power button.
