### ISSUE TITLE
PhhTrebleApp Crases When Trying to Access Duo-DE Features

### ISSUE THREAD

**Issue by GumbyXGames** [Archfx/duo-de#176]
### Acknowledgements

- [x] I have chosen an appropriate title.
- [x] All requested information has been provided properly.
- [x] This is not a feature request.
- [x] This issue is not a duplicate of an existing issue.
- [x] The issue is solely related to this GSI.
- [x] This issue occurs with the latest available build.
- [x] I am not running a custom vendor on my device.
- [x] This issue is not kernel related.
- [x] This issue is not related to Magisk/KernelSU/APatch.

### Info

Info

    Device: Duo 1
    GSI version: v2025.03.11 

### Expected Behavior

Open Duo-DE Treble Settings and opening the Duo-DE features menu to adjust settings

### Current Behavior

PhhTrebleApp crashes when trying to access Duo-DE features

### Possible Solution

Unknown

### Steps to Reproduce

1.     Open Android Settings
2.     Select DUO-DE Treble Settings
3.     Select DUO-DE features

### Logs

I will log as soon as I get to a computer. 

### Additional context

Same issue as #171

**Comment by GumbyXGames** [comment]
Sorry for the late log upload

[duo-de-issue-176.log](https://github.com/user-attachments/files/19200339/duo-de-issue-176.log)

**Comment by Ethanol10** [comment]
This log seems to show the same error that's been attempted to be fixed, You're certain this is v2025.03.11 yeah? 

@Archfx Error here:
```
03-11 21:04:20.627  8419  8419 D PHH     : Wireless Pen Charging preference removed for hardware: surfaceduo
03-11 21:04:20.627  8419  8419 D PHH     : Wireless Pen Charger during device charge preference removed for hardware: surfaceduo
03-11 21:04:20.627  8419  8419 D PHH     : Removed Pen Charging category for hardware: surfaceduo
03-11 21:04:20.628  8419  8419 D AndroidRuntime: Shutting down VM
--------- beginning of crash
03-11 21:04:20.628  8419  8419 E AndroidRuntime: FATAL EXCEPTION: main
03-11 21:04:20.628  8419  8419 E AndroidRuntime: Process: me.phh.treble.app, PID: 8419
03-11 21:04:20.628  8419  8419 E AndroidRuntime: java.lang.ClassCastException: androidx.preference.ListPreference cannot be cast to androidx.preference.SwitchPreference
03-11 21:04:20.628  8419  8419 E AndroidRuntime: 	at me.phh.treble.app.DuoSettingsFragment.onCreatePreferences(DuoSettings.kt:50)
03-11 21:04:20.628  8419  8419 E AndroidRuntime: 	at androidx.preference.PreferenceFragment.onCreate(PreferenceFragment.java:168)
03-11 21:04:20.628  8419  8419 E AndroidRuntime: 	at android.app.Fragment.performCreate(Fragment.java:2491)
03-11 21:04:20.628  8419  8419 E AndroidRuntime: 	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1261)
03-11 21:04:20.628  8419  8419 E AndroidRuntime: 	at android.app.FragmentManagerImpl.addAddedFragments(FragmentManager.java:2431)
03-11 21:04:20.628  8419  8419 E AndroidRuntime: 	at android.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2210)
03-11 21:04:20.628  8419  8419 E AndroidRuntime: 	at android.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2166)
03-11 21:04:20.628  8419  8419 E AndroidRuntime: 	at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2067)
03-11 21:04:20.628  8419  8419 E AndroidRuntime: 	at android.app.FragmentManagerImpl$1.run(FragmentManager.java:742)
03-11 21:04:20.628  8419  8419 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:959)
03-11 21:04:20.628  8419  8419 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:100)
03-11 21:04:20.628  8419  8419 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:232)
03-11 21:04:20.628  8419  8419 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:317)
03-11 21:04:20.628  8419  8419 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8705)
03-11 21:04:20.628  8419  8419 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
03-11 21:04:20.628  8419  8419 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
03-11 21:04:20.628  8419  8419 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:886)
03-11 21:04:20.630  3601  5529 I am_crash: [8419,0,me.phh.treble.app,550026949,java.lang.ClassCastException,androidx.preference.ListPreference cannot be cast to androidx.preference.SwitchPreference,DuoSettings.kt,50,0]
```

**Comment by GumbyXGames** [comment]
I did the OTA update. I'll double-check what build I'm on tonight. Didn't bring my Duo with me today

**Comment by GumbyXGames** [comment]
> This log seems to show the same error that's been attempted to be fixed, You're certain this is v2025.03.11 yeah?

Updater says I'm fully up to date. I'll dump a new fresh log just to be safe.

**Comment by Ethanol10** [comment]
@Archfx has the changed been pulled down into the build, it seems like that field is still recognising it as a SwitchPreference.

**Comment by GumbyXGames** [comment]
> [@Archfx](https://github.com/Archfx) has the changed been pulled down into the build, it seems like that field is still recognising it as a SwitchPreference.

Copy. Will await the next OTA.

**Comment by Archfx** [comment]
> [@Archfx](https://github.com/Archfx) has the changed been pulled down into the build, it seems like that field is still recognising it as a SwitchPreference.

As far as I remember, I synced all the repos. Let me update the device I have and check on this.

**Comment by GumbyXGames** [comment]
> > [@Archfx](https://github.com/Archfx) has the changed been pulled down into the build, it seems like that field is still recognising it as a SwitchPreference.
> 
> As far as I remember, I synced all the repos. Let me update the device I have and check on this.

This is an odd ask, but could I get the PhhTrebleApp apk from the latest build? Want to try something.

**Comment by Archfx** [comment]
> > > [@Archfx](https://github.com/Archfx) has the changed been pulled down into the build, it seems like that field is still recognising it as a SwitchPreference.
> > 
> > 
> > As far as I remember, I synced all the repos. Let me update the device I have and check on this.
> 
> This is an odd ask, but could I get the PhhTrebleApp apk from the latest build? Want to try something.

Due to how duo-de implements security, you won't be able to install system apps manually.

What is the current version of the duo-de version you are having? Looks like update didn't happen correctly.

**Comment by GumbyXGames** [comment]
> > > > [@Archfx](https://github.com/Archfx) has the changed been pulled down into the build, it seems like that field is still recognising it as a SwitchPreference.
> > > 
> > > 
> > > As far as I remember, I synced all the repos. Let me update the device I have and check on this.
> > 
> > 
> > This is an odd ask, but could I get the PhhTrebleApp apk from the latest build? Want to try something.
> 
> Due to how duo-de implements security, you won't be able to install system apps manually.
> 
> What is the current version of the duo-de version you are having? Looks like update didn't happen correctly.

Android says I'm fully up-to-date.

I can dump theapk via ADB so I should be able to push it to the device?

**Comment by Archfx** [comment]
> > > > > [@Archfx](https://github.com/Archfx) has the changed been pulled down into the build, it seems like that field is still recognising it as a SwitchPreference.
> > > > 
> > > > 
> > > > As far as I remember, I synced all the repos. Let me update the device I have and check on this.
> > > 
> > > 
> > > This is an odd ask, but could I get the PhhTrebleApp apk from the latest build? Want to try something.
> > 
> > 
> > Due to how duo-de implements security, you won't be able to install system apps manually.
> > What is the current version of the duo-de version you are having? Looks like update didn't happen correctly.
> 
> Android says I'm fully up-to-date.
> 
> I can dump theapk via ADB so I should be able to push it to the device?

Nope, this checks out. I couldn't check is on my device yet. Let me check it today. This could be a build time issue that occurred at my end.

**Comment by Archfx** [comment]
@GumbyXGames, this issue is not replicable on my side. It looks like it is due to the cache from the previous release that is still acting on your device. From the app settings, clean the cache and history of the treble app. It should fix this issue.

**Comment by GumbyXGames** [comment]
> [@GumbyXGames](https://github.com/GumbyXGames), this issue is not replicable on my side. It looks like it is due to the cache from the previous release that is still acting on your device. From the app settings, clean the cache and history of the treble app. It should fix this issue.

That didn't fix it. It's my only choice to flash the ROM again?

**Comment by Archfx** [comment]
Can you copy the `Settings->about device->Build number`, please. The last value should be `20250311.020417`. I think if the cache didn't fix, you are still on v2025.03.10.

**Comment by GumbyXGames** [comment]
Build# is `treble_arm64_bgN-userdebug 15 AP3A.241105.008 eng.aruna.20250311.020417`. As I mentioned, I made sure i was fully up-to-date. I'll just try flashing the ROM manually sometime this weekend. I'd still like to get the modified pphtrebble apk

**Comment by GumbyXGames** [comment]
Update: I manually flashed [aosp-arm64-ab-gapps-15.0-20250311.img.xz](https://github.com/Archfx/duo-de/releases/download/v2025.03.11/aosp-arm64-ab-gapps-15.0-20250311.img.xz) and phhtrebleapp still crashes when I try to access DUO-DE settings. Attached is a new log file

[phh_duo-de_settings_crash.log](https://github.com/user-attachments/files/19264933/phh_duo-de_settings_crash.log)

**Comment by Archfx** [comment]
I am not sure how this is happening. It is the same error. @GumbyXGames what are the steps you followed to clean the cache?

```shell
03-15 13:50:05.666  8285  8285 D PHH     : Removed Pen Charging category for hardware: surfaceduo
03-15 13:50:05.666  8285  8285 D AndroidRuntime: Shutting down VM
--------- beginning of crash
03-15 13:50:05.667  8285  8285 E AndroidRuntime: FATAL EXCEPTION: main
03-15 13:50:05.667  8285  8285 E AndroidRuntime: Process: me.phh.treble.app, PID: 8285
03-15 13:50:05.667  8285  8285 E AndroidRuntime: java.lang.ClassCastException: androidx.preference.ListPreference cannot be cast to androidx.preference.SwitchPreference
03-15 13:50:05.667  8285  8285 E AndroidRuntime: 	at me.phh.treble.app.DuoSettingsFragment.onCreatePreferences(DuoSettings.kt:50)
03-15 13:50:05.667  8285  8285 E AndroidRuntime: 	at androidx.preference.PreferenceFragment.onCreate(PreferenceFragment.java:168)
03-15 13:50:05.667  8285  8285 E AndroidRuntime: 	at android.app.Fragment.performCreate(Fragment.java:2491)
03-15 13:50:05.667  8285  8285 E AndroidRuntime: 	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1261)
03-15 13:50:05.667  8285  8285 E AndroidRuntime: 	at android.app.FragmentManagerImpl.addAddedFragments(FragmentManager.java:2431)
03-15 13:50:05.667  8285  8285 E AndroidRuntime: 	at android.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2210)
03-15 13:50:05.667  8285  8285 E AndroidRuntime: 	at android.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2166)
03-15 13:50:05.667  8285  8285 E AndroidRuntime: 	at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2067)
03-15 13:50:05.667  8285  8285 E AndroidRuntime: 	at android.app.FragmentManagerImpl$1.run(FragmentManager.java:742)
03-15 13:50:05.667  8285  8285 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:959)
03-15 13:50:05.667  8285  8285 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:100)
03-15 13:50:05.667  8285  8285 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:232)
03-15 13:50:05.667  8285  8285 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:317)
03-15 13:50:05.667  8285  8285 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8705)
03-15 13:50:05.667  8285  8285 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
03-15 13:50:05.667  8285  8285 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
03-15 13:50:05.667  8285  8285 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:886)
```

**Comment by GumbyXGames** [comment]
> I am not sure how this is happening. It is the same error. [@GumbyXGames](https://github.com/GumbyXGames) what are the steps you followed to clean the cache?
> 
> 03-15 13:50:05.666  8285  8285 D PHH     : Removed Pen Charging category for hardware: surfaceduo
> 03-15 13:50:05.666  8285  8285 D AndroidRuntime: Shutting down VM
> --------- beginning of crash
> 03-15 13:50:05.667  8285  8285 E AndroidRuntime: FATAL EXCEPTION: main
> 03-15 13:50:05.667  8285  8285 E AndroidRuntime: Process: me.phh.treble.app, PID: 8285
> 03-15 13:50:05.667  8285  8285 E AndroidRuntime: java.lang.ClassCastException: androidx.preference.ListPreference cannot be cast to androidx.preference.SwitchPreference
> 03-15 13:50:05.667  8285  8285 E AndroidRuntime: 	at me.phh.treble.app.DuoSettingsFragment.onCreatePreferences(DuoSettings.kt:50)
> 03-15 13:50:05.667  8285  8285 E AndroidRuntime: 	at androidx.preference.PreferenceFragment.onCreate(PreferenceFragment.java:168)
> 03-15 13:50:05.667  8285  8285 E AndroidRuntime: 	at android.app.Fragment.performCreate(Fragment.java:2491)
> 03-15 13:50:05.667  8285  8285 E AndroidRuntime: 	at android.app.FragmentManagerImpl.moveToState(FragmentManager.java:1261)
> 03-15 13:50:05.667  8285  8285 E AndroidRuntime: 	at android.app.FragmentManagerImpl.addAddedFragments(FragmentManager.java:2431)
> 03-15 13:50:05.667  8285  8285 E AndroidRuntime: 	at android.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2210)
> 03-15 13:50:05.667  8285  8285 E AndroidRuntime: 	at android.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2166)
> 03-15 13:50:05.667  8285  8285 E AndroidRuntime: 	at android.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2067)
> 03-15 13:50:05.667  8285  8285 E AndroidRuntime: 	at android.app.FragmentManagerImpl$1.run(FragmentManager.java:742)
> 03-15 13:50:05.667  8285  8285 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:959)
> 03-15 13:50:05.667  8285  8285 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:100)
> 03-15 13:50:05.667  8285  8285 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:232)
> 03-15 13:50:05.667  8285  8285 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:317)
> 03-15 13:50:05.667  8285  8285 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8705)
> 03-15 13:50:05.667  8285  8285 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
> 03-15 13:50:05.667  8285  8285 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
> 03-15 13:50:05.667  8285  8285 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:886)

I go into the **Apps** menu under **Settings,** go to the full Apps list, search for * PhhTrebleApp**, select the app, open **Storage & cache**, and ***Clear cache**.
